### PR TITLE
Streaming updates

### PR DESCRIPTION
**Pull request by khalillechelt**
Refactoring to make changes to the localStorage & sessionStorage streaming.

### CODE REVIEW

**Comment by khalillechelt** [comment]
@staltz @TylorS this is ready for a review if you fancy it?

**Comment by staltz** [comment]
I mainly reviewed the driver source and the example. Looks ok to me!

**Comment by khalillechelt** [comment]
Cool, thanks! I'll just go ahead and merge away.

**Comment by staltz** [comment]
:+1:

**Pull request merged**
