### PR TITLE
refactor(upgrade): Update to Unified

### PR DESCRIPTION
**Pull request by ntilwalli**
Update storage driver to Cycle Unified

@staltz

### CODE REVIEW

**Comment by staltz** [comment]
Thanks @ntilwalli 
I'll release a new version, but I don't have time for maintaining this repo, so I'll leave the ownership with @kahlil, unless someone wants to volunteer maintaining this.

**Comment by mightyiam** [comment]
:fireworks:

**Comment by ntilwalli** [comment]
@staltz You could give it to me.  It would be low priority for me but I have been maintaining it recently for my own purposes

**Comment by staltz** [comment]
Done :)

**Comment by ntilwalli** [comment]
@staltz Cool.  Did you include npm publish privileges or will you continue to admin that?  Also does this repo merit being moved to cyclejs-community?

**Comment by staltz** [comment]
Yes npm as well

> Also does this repo merit being moved to cyclejs-community?

That's a harder question. It's already in `@cycle/storage` so it wouldn't be nice to break it out from there and leave a package hole. I didn't start the cyclejs-community group so I don't know what are the guidelines of what goes where. I'm okay with this repo staying here. So far we've seen repos coming from elsewhere (cyclejs-community or under my own `/staltz`) to here, but not yet the opposite.

**Comment by mightyiam** [comment]
My two cents is that if it is groomed to a fine shape then it could be an official driver in the monorepo.

**Comment by khalillechelt** [comment]
Oh I am only seeing now that I was mentioned here @staltz, sorry. 
@ntilwalli thanks for taking over! 
I have not maintained this in a long time and I am out of the loop here since Cycle Diversity 😃

**Comment by mightyiam** [comment]
@kahlil, if it changes anything, I'm letting you know that Cycle.js has been been since reunified on xstream.

**Comment by khalillechelt** [comment]
@mightyiam I am well aware, thank you. The thing is I don't get to write Cycle code at work and I don't want to split my attention in two frameworks at the moment. This is why is no real headspace or interest for me to keep maintaining this. There is no benefit for me in maintaining this and I can't eat my own dog food either when it comes to this. 

I am happy if somebody can take this over who actually uses it and writes Cycle code on a regular basis.

**Pull request merged**
